DECLARE 
    @DATA_INICIO DATE = CAST(FORMAT(GETDATE(), 'yyyy-MM-01') AS DATE),
    @DATA_FIM DATE = CAST(EOMONTH(GETDATE()) AS DATE);

WITH 
HC_BASE AS (
    SELECT
        --  HC no início do período
        COUNT(DISTINCT(CASE WHEN DT_ADMISSAO <= @DATA_INICIO 
							AND (DT_DEMISSAO IS NULL OR DT_DEMISSAO > @DATA_INICIO)
							AND DS_SITUACAO IN ('Ativo', 'Experiência', 'Férias')
						THEN ID_CHAPA_LEGADO END)) AS HC_INICIO,
        
        --  HC no fim do período
        COUNT(DISTINCT(CASE WHEN DT_ADMISSAO <= @DATA_FIM 
							AND (DT_DEMISSAO IS NULL OR DT_DEMISSAO > @DATA_FIM)
							AND DS_SITUACAO IN ('Ativo', 'Experiência', 'Férias')
						THEN ID_CHAPA_LEGADO END)) AS HC_FIM,
        
        --  demissões no período
         COUNT(DISTINCT(CASE WHEN DT_DEMISSAO BETWEEN @DATA_INICIO AND @DATA_FIM
						THEN ID_CHAPA_LEGADO END)) AS DEMITIDOS,

		--	contratações no periodo
		 COUNT(DISTINCT(CASE WHEN DT_ADMISSAO BETWEEN @DATA_INICIO AND @DATA_FIM	
						THEN ID_CHAPA_LEGADO END)) AS CONTRATADOS,

		-- desligados voluntarios no periodo
		 COUNT(DISTINCT(CASE WHEN DT_DEMISSAO BETWEEN @DATA_INICIO AND @DATA_FIM
							 AND DS_TIPO_DEMISSAO IN ( 'INICIATIVA EMPREGADO SEM JUSTA CAUSA', 'COMUM ACORDO', 'OUTROS CASOS' )
						THEN ID_CHAPA_LEGADO END)) AS DEMITIDOS_VOLUNTARIO

    FROM 
		FT_RH_FUNCIONARIOS

	WHERE 
		DT_REFERENCIA >= @DATA_INICIO
		AND SK_CONTROLADORIA_EMPRESA = 1
	)

,	QUADRO AS (
	SELECT
		-- QUADRO
		SUM(A.QTD_APROVADO) AS QUADRO

	FROM
		FT_RH_FUNCIONARIOS_QUADRO_APROVADO A

	INNER JOIN 
		DIM_LOJA B
		ON B.SK_LOJA = A.SK_LOJA
		AND DT_INAUGURACAO_LOJA > '19511201'


	WHERE A.DT_REFERENCIA BETWEEN @DATA_INICIO AND @DATA_FIM 
	)

, HC AS (
	SELECT
        --  HC 
		COUNT(DISTINCT(CASE WHEN DT_ADMISSAO <= @DATA_FIM 
							AND (DT_DEMISSAO IS NULL OR DT_DEMISSAO > @DATA_FIM)
							AND DS_SITUACAO IN ('Ativo', 'Experiência', 'Férias')
						THEN ID_CHAPA_LEGADO END)) AS HC_FIM

    FROM 
		FT_RH_FUNCIONARIOS A

	INNER JOIN
		DIM_LOJA B
		ON B.SK_LOJA = A.SK_LOJA
		AND DS_CLASSIFICACAO_LOJA = 'LOJA'
		AND DT_INAUGURACAO_LOJA > '19511201'

	WHERE 
		DT_REFERENCIA >= @DATA_INICIO
		AND SK_CONTROLADORIA_EMPRESA = 1
		AND SK_FUNCAO  IN
		(742
		,770
		,2791
		,690
		,2835
		,926
		,734
		,2062
		,1662
		,706
		,810
		,738
		,798
		,778
		)		
	)

,	VAGAS_ABERTAS AS (
	SELECT
		SUM(A.QUADRO)			   AS QUADRO,
		ISNULL(SUM(B.HC_FIM),0)	   AS HC,
		CAST(GETDATE() -1 AS date) AS  DATA
	
	FROM 
		QUADRO A
	
	CROSS JOIN
		HC B
	)

SELECT
	B.DATA,
    HC_FIM											AS HEADCOUNT,
	CONTRATADOS,
    DEMITIDOS,
	DEMITIDOS * 1.0 / HC_FIM	* 1.0				AS '%_DESLIGAMENTO',
	DEMITIDOS_VOLUNTARIO,
	DEMITIDOS_VOLUNTARIO * 1.0 / DEMITIDOS * 1.0	AS '%_DESLIGADOS_VOLUNTARIO',
	--- CALCULO DO TURNOVER SE DÁ POR ((CONTRATADOS + DESLIGADOS) / 2) / ((HC_INICIO DO MES + HC_FIM DO MES)/2)
        ((DEMITIDOS + CONTRATADOS) /2) / 
        ((HC_INICIO + HC_FIM) / 2.0)				AS '%_TURNOVER',
	(QUADRO - HC)									AS VAGAS_ABERTAS

FROM 
	HC_BASE A

CROSS JOIN
	VAGAS_ABERTAS B
	


	