WITH 
RUPTURA AS (
	SELECT
		B.DATA,
		C.DS_CURVA_REDE,
		SUM(VL_TOTAL) AS VL_RUPTURA

	FROM 
		[DW].[dbo].FT_RUPTURA A

	INNER JOIN 
		[DW].[dbo].DIM_PERIODO B
		ON B.SK_DATA = A.SK_DATA
		AND MONTH(B.DATA) = MONTH(GETDATE())
		AND (YEAR(B.DATA) = YEAR(GETDATE()) OR YEAR(B.DATA) = YEAR(GETDATE()) - 1)
		AND NR_DIA <= DAY(CAST(GETDATE() -1 AS date))

	INNER JOIN
		[DW].[dbo].DIM_PRODUTO C
		ON C.SK_PRODUTO = A.SK_PRODUTO
		AND C.CD_GRUPO_PRODUTO <> '39'

	GROUP BY 
		B.DATA,
		DS_CURVA_REDE

),

VENDAS AS (
	SELECT
		DATA,
		A.CURVA,
		SUM(VL_VENDA) AS VL_VENDA

	FROM 
		[DW].[dbo].FT_EMAIL_DIRETORIA_VENDAS_IMPOSTOS A

	WHERE 
		 DAY(DATA) <= DAY(CAST(GETDATE() -1 AS date))

	GROUP BY 
		DATA,
		CURVA
),

BASE_AGREGADA AS (
	SELECT
		A.DATA,
		A.VL_RUPTURA,
		A.DS_CURVA_REDE AS CURVA,
		B.VL_VENDA,
		CAST(A.VL_RUPTURA AS FLOAT) / NULLIF(B.VL_VENDA, 0) AS PCT_RUPTURA,
		CAST(A.VL_RUPTURA AS FLOAT) AS RUPTURA_DIA
	
	FROM 
		RUPTURA A
	
	LEFT JOIN 
		VENDAS B
		ON A.DATA = B.DATA
		AND A.DS_CURVA_REDE = B.CURVA
),

BASE_AGREGADA_TOTAL AS (
	SELECT
		A.DATA,
		SUM(A.VL_RUPTURA) AS VL_RUPTURA,
		SUM(B.VL_VENDA) AS VL_VENDA,
		SUM(CAST(A.VL_RUPTURA AS FLOAT)) / SUM(NULLIF(B.VL_VENDA, 0)) AS PCT_RUPTURA,
		SUM(CAST(A.VL_RUPTURA AS FLOAT)) AS RUPTURA_DIA
	
	FROM 
		RUPTURA A
	
	LEFT JOIN 
		VENDAS B
		ON A.DATA = B.DATA
		AND A.DS_CURVA_REDE = B.CURVA

	GROUP BY
		A.DATA
),

DF_FINAL AS (
	SELECT
		ATUAL.DATA,
		ATUAL.RUPTURA_DIA,
		ATUAL.CURVA,
		ATUAL.PCT_RUPTURA,

		-- Acumulado de ruptura
		SUM(ATUAL.RUPTURA_DIA) OVER (
			PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA), ATUAL.CURVA
			ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
		) AS RUPTURA_ACUMULADA,

		-- ruptura acumulada ano anterior
		SUM(ANT.RUPTURA_DIA) OVER (
			PARTITION BY YEAR(ANT.DATA), MONTH(ANT.DATA), ATUAL.CURVA
			ORDER BY ANT.DATA ROWS UNBOUNDED PRECEDING
		) AS RUPTURA_ACUMULADA_A1,

		-- Acumulado de venda
		SUM(ATUAL.VL_VENDA) OVER (
			PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA), ATUAL.CURVA
			ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
		) AS VENDA_ACUMULADA,

		-- % ruptura acumulada
		CAST(SUM(ATUAL.RUPTURA_DIA) OVER (
			PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA), ATUAL.CURVA
			ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
		) AS FLOAT) / 
		NULLIF(SUM(ATUAL.VL_VENDA) OVER (
			PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA), ATUAL.CURVA
			ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
		), 0) AS PCT_RUPTURA_ACUMULADA,

		-- Crescimento acumulado R$ Ruptura YoY
		(
			SUM(ATUAL.RUPTURA_DIA) OVER (
				PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA), ATUAL.CURVA
				ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
			)
			/
			NULLIF(SUM(ANT.RUPTURA_DIA) OVER (
				PARTITION BY YEAR(ANT.DATA), MONTH(ANT.DATA), ATUAL.CURVA
				ORDER BY ANT.DATA ROWS UNBOUNDED PRECEDING
			), 0)
		) - 1 AS CRESC_RUPTURA_ACUMULADA,

		-- Variação em pontos percentuais da ruptura acumulada
		(
			CAST(SUM(ATUAL.RUPTURA_DIA) OVER (
				PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA), ATUAL.CURVA
				ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
			) AS FLOAT) / 
			NULLIF(SUM(ATUAL.VL_VENDA) OVER (
				PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA), ATUAL.CURVA
				ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
			), 0)
		) -
		(
			CAST(SUM(ANT.RUPTURA_DIA) OVER (
				PARTITION BY YEAR(ANT.DATA), MONTH(ANT.DATA), ATUAL.CURVA
				ORDER BY ANT.DATA ROWS UNBOUNDED PRECEDING
			) AS FLOAT) / 
			NULLIF(SUM(ANT.VL_VENDA) OVER (
				PARTITION BY YEAR(ANT.DATA), MONTH(ANT.DATA), ATUAL.CURVA
				ORDER BY ANT.DATA ROWS UNBOUNDED PRECEDING
			), 0)
		) AS VAR_PP_RUPTURA_ACUMULADA

	FROM 
		BASE_AGREGADA ATUAL
	LEFT JOIN 
		BASE_AGREGADA ANT
		ON ANT.DATA = DATEADD(YEAR, -1, ATUAL.DATA)
		AND ATUAL.CURVA = ANT.CURVA
)


, DF_FINAL_TOTAL as (
	SELECT
		ATUAL.DATA,
		ATUAL.RUPTURA_DIA,
		ATUAL.PCT_RUPTURA,

		-- Acumulado de ruptura
		SUM(ATUAL.RUPTURA_DIA) OVER (
			PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA)
			ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
		) AS RUPTURA_ACUMULADA,

		-- ruptura acumulada ano anterior
		SUM(ANT.RUPTURA_DIA) OVER (
			PARTITION BY YEAR(ANT.DATA), MONTH(ANT.DATA)
			ORDER BY ANT.DATA ROWS UNBOUNDED PRECEDING
		) AS RUPTURA_ACUMULADA_A1,

		-- Acumulado de venda
		SUM(ATUAL.VL_VENDA) OVER (
			PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA)
			ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
		) AS VENDA_ACUMULADA,

		-- % ruptura acumulada
		CAST(SUM(ATUAL.RUPTURA_DIA) OVER (
			PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA)
			ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
		) AS FLOAT) / 
		NULLIF(SUM(ATUAL.VL_VENDA) OVER (
			PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA)
			ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
		), 0) AS PCT_RUPTURA_ACUMULADA,

		-- Crescimento acumulado R$ Ruptura YoY
		(
			SUM(ATUAL.RUPTURA_DIA) OVER (
				PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA)
				ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
			)
			/
			NULLIF(SUM(ANT.RUPTURA_DIA) OVER (
				PARTITION BY YEAR(ANT.DATA), MONTH(ANT.DATA)
				ORDER BY ANT.DATA ROWS UNBOUNDED PRECEDING
			), 0)
		) - 1 AS CRESC_RUPTURA_ACUMULADA,

		-- Variação em pontos percentuais da ruptura acumulada
		(
			CAST(SUM(ATUAL.RUPTURA_DIA) OVER (
				PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA)
				ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
			) AS FLOAT) / 
			NULLIF(SUM(ATUAL.VL_VENDA) OVER (
				PARTITION BY YEAR(ATUAL.DATA), MONTH(ATUAL.DATA)
				ORDER BY ATUAL.DATA ROWS UNBOUNDED PRECEDING
			), 0)
		) -
		(
			CAST(SUM(ANT.RUPTURA_DIA) OVER (
				PARTITION BY YEAR(ANT.DATA), MONTH(ANT.DATA)
				ORDER BY ANT.DATA ROWS UNBOUNDED PRECEDING
			) AS FLOAT) / 
			NULLIF(SUM(ANT.VL_VENDA) OVER (
				PARTITION BY YEAR(ANT.DATA), MONTH(ANT.DATA)
				ORDER BY ANT.DATA ROWS UNBOUNDED PRECEDING
			), 0)
		) AS VAR_PP_RUPTURA_ACUMULADA

	FROM 
		BASE_AGREGADA_TOTAL ATUAL
	LEFT JOIN 
		BASE_AGREGADA_TOTAL ANT
		ON ANT.DATA = DATEADD(YEAR, -1, ATUAL.DATA)


	)
SELECT 
	'CURVA'													AS Nivel,
	CAST(DATA AS date) 										AS DATA,
	DF_FINAL.CURVA 											AS CURVA,
	RUPTURA_DIA												AS 'R$_RUPTURA_ONTEM',	
	RUPTURA_ACUMULADA										AS 'R$_RUPTURA_ACUMULADA',
	PCT_RUPTURA												AS '%_RUPTURA_ONTEM',
	PCT_RUPTURA_ACUMULADA									AS '%_RUPTURA_ACUMULADA',
	CRESC_RUPTURA_ACUMULADA									AS '%_CRESC_RUPTURA_A-1',
	CAST(VAR_PP_RUPTURA_ACUMULADA * 100 AS decimal(6,2))	AS 'VAR_PP_RUPTURA_ACUMULADA'

FROM DF_FINAL
WHERE DATA = CAST(GETDATE() - 1 AS DATE)

UNION ALL

SELECT 
	'TOTAL GERAL'											AS Nivel,
	CAST(DATA AS date) 										AS DATA,
	'VENANCIO'												AS CURVA,
	RUPTURA_DIA												AS 'R$_RUPTURA_ONTEM',	
	RUPTURA_ACUMULADA										AS 'R$_RUPTURA_ACUMULADA',
	PCT_RUPTURA												AS '%_RUPTURA_ONTEM',
	PCT_RUPTURA_ACUMULADA									AS '%_RUPTURA_ACUMULADA',
	CRESC_RUPTURA_ACUMULADA									AS '%_CRESC_RUPTURA_A-1',
	CAST(VAR_PP_RUPTURA_ACUMULADA * 100 AS decimal(6,2))	AS 'VAR_PP_RUPTURA_ACUMULADA'

FROM DF_FINAL_TOTAL
WHERE DATA = CAST(GETDATE() - 1 AS DATE)
ORDER BY Nivel DESC, CURVA ASC