WITH
----- BASE DE VENDAS E IMPOSTOS ----
	BASE AS (

		SELECT 
			FORMAT(EOMONTH(DATA), 'yyyy-MM-01')					AS DATA,
			SUM(CASE WHEN DEVOLUCAO = 0 THEN VL_VENDA END)		AS RECEITA_BRUTA,
			SUM(CASE WHEN DEVOLUCAO = 1 THEN VL_VENDA END)		AS DEVOLUCOES,
			SUM(VL_COFINS)										AS VL_COFINS,
			SUM(VL_CMV)											AS VL_CMV,
			SUM(VL_ICMS)										AS VL_ICMS,
			SUM(VL_DIFAL)										AS VL_DIFAL,
			SUM(VL_PIS)											AS VL_PIS
		
		FROM 
			DW.DBO.FT_EMAIL_DIRETORIA_VENDAS_IMPOSTOS A
		
		WHERE CAST(DATA AS date) < CAST(GETDATE() -4 AS date)

		GROUP BY
			CAST(EOMONTH(DATA) AS date)	
		)

----- BASE REEMBOLSO CONTRATOS -----
,	REEMBOLSO_CONTRATOS AS (

		SELECT	
			FORMAT(EOMONTH(DATA), 'yyyy-MM-01') AS DATA,
			SUM(VL_REEMBOLSO)  AS REEMBOLSO_CONTRATO

		FROM 
			DW.DBO.FT_REEMBOLSO_CONTRATOS A

		INNER JOIN
			DW.DBO.DIM_PRODUTO B
			ON B.SK_PRODUTO = A.SK_PRODUTO
			AND B.CD_GRUPO_PRODUTO <> '39'

		INNER JOIN
			DW.DBO.DIM_PERIODO C
			ON C.SK_DATA = A.SK_DATA
			AND MONTH(DATA) = MONTH(GETDATE())
			AND (YEAR(DATA) = YEAR(GETDATE()) OR YEAR(DATA) = YEAR(GETDATE()) -1)

		WHERE 
			CAST(DATA AS date) < CAST(GETDATE() - 4 AS date)

		GROUP BY
			CAST(EOMONTH(DATA) AS date)
	)

---- BASE REEMBOLSO PBM ----
,	REEMBOLSO_PBM AS (

		SELECT
			FORMAT(EOMONTH(DATA), 'yyyy-MM-01')		AS DATA,
			SUM(VL_REEMBOLSO_TOTAL)					AS REEMBOLSO_PBM

		FROM
			DW.DBO.FT_REEMBOLSO_PBM_PRODUTO_LOJA A

		INNER JOIN
			DW.DBO.DIM_PRODUTO B
			ON B.SK_PRODUTO = A.SK_PRODUTO
			AND B.CD_GRUPO_PRODUTO <> '39'

		INNER JOIN
			DW.DBO.DIM_PERIODO C
			ON C.SK_DATA = A.SK_DATA
			AND MONTH(DATA) = MONTH(GETDATE())
			AND (YEAR(DATA) = YEAR(GETDATE()) OR YEAR(DATA) = YEAR(GETDATE()) -1)

		WHERE CAST(DATA AS date) < CAST(GETDATE() - 4 AS date)

		GROUP BY
			CAST(EOMONTH(DATA) AS date)
	)

, CTE_AGG AS (
SELECT
	A.DATA																																																								    AS DATA,
	(ISNULL(RECEITA_BRUTA,0) + ISNULL(B.REEMBOLSO_CONTRATO,0) + ISNULL(C.REEMBOLSO_PBM,0) + ISNULL(DEVOLUCOES,0)) -  (ISNULL(VL_COFINS,0) + ISNULL(VL_CMV,0) + ISNULL(VL_ICMS,0) + ISNULL(VL_DIFAL,0) + ISNULL(VL_PIS,0))				    AS LUCRO_BRUTO,
	((ISNULL(RECEITA_BRUTA,0) + ISNULL(B.REEMBOLSO_CONTRATO,0) + ISNULL(C.REEMBOLSO_PBM,0) + ISNULL(DEVOLUCOES,0)) -  (ISNULL(VL_COFINS,0) + ISNULL(VL_CMV,0) + ISNULL(VL_ICMS,0) + ISNULL(VL_DIFAL,0) + ISNULL(VL_PIS,0))) / RECEITA_BRUTA AS MARGEM_BRUTA

FROM
	BASE A

LEFT JOIN
	REEMBOLSO_CONTRATOS B
	ON B.DATA = A.DATA
	
LEFT JOIN
	REEMBOLSO_PBM C
	ON C.DATA = A.DATA
	)

,	META AS (
	SELECT FORMAT(B.DATA_SIMPLES, 'yyyy-MM-01') AS DATA
	      ,SUM([META_VENDA]) AS META_VENDA
	      ,SUM([META_LUCRO_BRUTO]) AS META_LUCRO_BRUTO
		  ,SUM(META_LUCRO_BRUTO) / SUM(META_VENDA) AS META_MARGEM
	 
	FROM 
		[DW].[dbo].[FT_METAS_INTELIGENCIA_GR_COMPRA_2025] A
	 
	INNER JOIN 
		[DW].[dbo].DIM_PERIODO B 
		ON A.SK_DATA = B.SK_DATA
		AND B.DATA >= FORMAT(GETDATE(), 'yyyy-MM-01')
		AND B.DATA < EOMONTH(GETDATE())
	 
	 
	  GROUP BY FORMAT(B.DATA_SIMPLES, 'yyyy-MM-01')
	)

	----------------------------------------------------------------------------------------------
	------SEMPRE CALCULADO D-4 POIS CMV E RECOMPOSIÇÃO ESTÃO SEGUINDO ESSA REGRA:  11-06-2025-----
	----------------------------------------------------------------------------------------------
SELECT 
	CAST(ATUAL.DATA as date) AS MES
	, ATUAL.LUCRO_BRUTO
	, M.META_LUCRO_BRUTO
	, (ATUAL.LUCRO_BRUTO / M.META_LUCRO_BRUTO)												AS ALCANCE_META_LUCRO
	, ATUAL.MARGEM_BRUTA																	AS MARGEM_BRUTA	
	, (ATUAL.MARGEM_BRUTA / M.META_MARGEM)													AS ALCANCE_META_MARGEM
	, ANTERIOR.MARGEM_BRUTA																	AS 'MARGEM_BRUTA_A-1'
	, CAST(ROUND(( ATUAL.MARGEM_BRUTA - ANTERIOR.MARGEM_BRUTA ) * 100,3) AS decimal(6,2))	AS DIFERENCA_MARGEM_PP
FROM 
	CTE_AGG ATUAL

INNER JOIN 
	CTE_AGG ANTERIOR
	ON ANTERIOR.DATA = DATEADD(YEAR, -1, ATUAL.DATA) 

LEFT JOIN
	META M 
	ON M.DATA = ATUAL.DATA

