WITH
QUEBRA AS (
    SELECT
        DATA,
        C.DS_MOTIVOS_TRANSFERENCIAS AS MOTIVO,
        SUM(VL_QUEBRA) AS VL_QUEBRA
    FROM 
        FT_QUEBRA A
    INNER JOIN 
        DIM_PERIODO B ON B.SK_DATA = A.SK_DATA
        AND MONTH(DATA) = MONTH(GETDATE())
        AND (YEAR(DATA) = YEAR(GETDATE()) OR YEAR(DATA) = YEAR(GETDATE()) - 1)
        AND NR_DIA < DAY(GETDATE() -4)
    INNER JOIN
        DIM_MOTIVOS_TRANSFERENCIAS C ON C.SK_MOTIVOS_TRANSFERENCIAS = A.SK_MOTIVOS_TRANSFERENCIAS
    GROUP BY
        DATA, C.DS_MOTIVOS_TRANSFERENCIAS
),

BASE AS (
    SELECT
        Q.DATA,
        Q.MOTIVO,
        Q.VL_QUEBRA
    FROM 
        QUEBRA Q
),

BASE_ACUMULADA AS (
    SELECT
        DATA,
        MOTIVO,
        VL_QUEBRA,
        SUM(VL_QUEBRA) OVER (
            PARTITION BY MOTIVO, YEAR(DATA), MONTH(DATA)
            ORDER BY DATA
            ROWS UNBOUNDED PRECEDING
        ) AS VL_QUEBRA_ACUMULADA
    FROM
        BASE
),

BASE_ACUMULADA_YOY AS (
    SELECT
        *
    FROM 
        BASE_ACUMULADA
),

ULTIMOS_DIAS AS (
    SELECT
        MOTIVO,
        MAX(DATA) AS ULTIMA_DATA
    FROM
        BASE_ACUMULADA_YOY
    WHERE
        DATA < CAST(GETDATE() - 4 AS DATE)
    GROUP BY
        MOTIVO
)

SELECT
    CAST(B.DATA AS DATE) AS DATA,
    B.MOTIVO,
    B.VL_QUEBRA													AS R$_QUEBRA_ONTEM,
    B.VL_QUEBRA_ACUMULADA										AS R$_QUEBRA_ACUMULADA

FROM
    BASE_ACUMULADA_YOY B
JOIN
    ULTIMOS_DIAS U
    ON B.MOTIVO = U.MOTIVO AND B.DATA = U.ULTIMA_DATA

WHERE  1=1
        AND MONTH(DATA) = MONTH(GETDATE())
        AND YEAR(DATA) = YEAR(GETDATE())
UNION

SELECT
	FORMAT(CAST(DATEADD(DAY, -1, GETDATE()) AS DATE), 'yyyy-MM-dd') AS DATA,
	'TOTAL GERAL QUEBRA' AS MOTIVO,
	SUM(B.VL_QUEBRA) AS R$_QUEBRA_ONTEM,
	SUM(B.VL_QUEBRA_ACUMULADA) AS R$_QUEBRA_ACUMULADA

FROM 
	BASE_ACUMULADA_YOY B

JOIN
    ULTIMOS_DIAS U
    ON B.MOTIVO = U.MOTIVO AND B.DATA = U.ULTIMA_DATA

WHERE  1=1
        AND MONTH(DATA) = MONTH(GETDATE())
        AND YEAR(DATA) = YEAR(GETDATE())

GROUP BY
	EOMONTH(DATA)

ORDER BY 3 DESC